### ISSUE TITLE
大佬,选择完的照片可以增加个圆角显示吗

### ISSUE THREAD

**Issue by lydlovezjr** [LwkCoder/NineGridView#14]
现在添加图片的那个图片是带圆角的.
然后选择完成以后,的图片还是直角的.
是否有属性可以设置是否开启圆角和圆角的大小.

如果没有的话,是否考虑增加.

**Comment by LwkCoder** [comment]
@lydlovezjr 
同学你好，首先解答下你的问题
该组件内置的图片控件本身不支持圆角显示，但是你可以自定义一下图片加载器，用Glide增加圆角显示功能，步骤如下：
1.自定义类实现接口`INgvImageLoader`，在load方法里用Glide增加圆角裁剪并显示到相应的ImageView上。
2.将你自定义的imageloader设置给NineGridView即可。

这个步骤请自行实现，因为目前我已经不再从事开发工作了，后续也不打算维护相关组件了，请谅解。

**Comment by lydlovezjr** [comment]
好的,感谢大佬
